// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transactor

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTeeService creates a new instance of MockTeeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeeService {
	mock := &MockTeeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeeService is an autogenerated mock type for the TeeService type
type MockTeeService struct {
	mock.Mock
}

type MockTeeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeeService) EXPECT() *MockTeeService_Expecter {
	return &MockTeeService_Expecter{mock: &_m.Mock}
}

// GetQuote provides a mock function for the type MockTeeService
func (_mock *MockTeeService) GetQuote(userData []byte) ([]byte, error) {
	ret := _mock.Called(userData)

	if len(ret) == 0 {
		panic("no return value specified for GetQuote")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(userData)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(userData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeeService_GetQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuote'
type MockTeeService_GetQuote_Call struct {
	*mock.Call
}

// GetQuote is a helper method to define mock.On call
//   - userData []byte
func (_e *MockTeeService_Expecter) GetQuote(userData interface{}) *MockTeeService_GetQuote_Call {
	return &MockTeeService_GetQuote_Call{Call: _e.mock.On("GetQuote", userData)}
}

func (_c *MockTeeService_GetQuote_Call) Run(run func(userData []byte)) *MockTeeService_GetQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTeeService_GetQuote_Call) Return(bytes []byte, err error) *MockTeeService_GetQuote_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTeeService_GetQuote_Call) RunAndReturn(run func(userData []byte) ([]byte, error)) *MockTeeService_GetQuote_Call {
	_c.Call.Return(run)
	return _c
}
